In [2]:
import polars as pl
import requests
import time
import random
import logging
from typing import Dict, Any, List, Optional
from datetime import datetime

In [24]:
df = pl.read_parquet("/Users/yakto/projects/career_agent/data_artefacts/vacancy_final.parquet")
df1 = pl.read_parquet("/Users/yakto/projects/career_agent/parser/data/*")
df1 = df1.with_columns([
    pl.col('published_at').str.strptime(pl.Datetime, format='%Y-%m-%dT%H:%M:%S%z'),
    pl.col('salary_from').cast(pl.Int64),
    pl.col('salary_to').cast(pl.Int64),
]).unique(subset=['vacancy_id'])
df1 = df1.with_columns(pl.col('vacancy_id').cast(pl.Int64).alias('vacancy_id'))

In [8]:
df = pl.read_parquet("/Users/yakto/projects/career_agent/data_artefacts/vacancy_final.parquet")
df

shape: (12_399, 18)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ vacancy_i ┆ title     ┆ loc       ┆ requireme ┆ … ┆ salary_st ┆ url       ┆ published ┆ source_v │
│ d         ┆ ---       ┆ ---       ┆ nt        ┆   ┆ r         ┆ ---       ┆ _at       ┆ acancy   │
│ ---       ┆ str       ┆ str       ┆ ---       ┆   ┆ ---       ┆ str       ┆ ---       ┆ ---      │
│ str       ┆           ┆           ┆ str       ┆   ┆ str       ┆           ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 129783890 ┆ AI        ┆ Алматы    ┆ За        ┆ … ┆ 500000-   ┆ https://h ┆ 2026-01-2 ┆ AI       │
│           ┆ Engineer  ┆           ┆ проектом  ┆   ┆ KZT       ┆ h.ru/vaca ┆ 3T09:28:5 ┆ engineer │
│           ┆ (Middle / ┆           ┆ уже есть  ┆   ┆           ┆ ncy/12978 ┆ 1+0300    ┆          │
│           ┆ Middle+ … ┆           ┆ подтвержд ┆   ┆           ┆ 389…      ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ 129788643 ┆ MLOps     ┆ Москва    ┆ Опыт      ┆ … ┆ з/п не    ┆ https://h ┆ 2026-01-2 ┆ AI       │
│           ┆ Engineer  ┆           ┆ работы в  ┆   ┆ указана   ┆ h.ru/vaca ┆ 3T10:44:5 ┆ engineer │
│           ┆           ┆           ┆ роли      ┆   ┆           ┆ ncy/12978 ┆ 1+0300    ┆          │
│           ┆           ┆           ┆ MLOps     ┆   ┆           ┆ 864…      ┆           ┆          │
│           ┆           ┆           ┆ <high…    ┆   ┆           ┆           ┆           ┆          │
│ 129410280 ┆ AI        ┆ Москва    ┆ Способнос ┆ … ┆ з/п не    ┆ https://h ┆ 2026-01-2 ┆ AI       │
│           ┆ product   ┆           ┆ ть самост ┆   ┆ указана   ┆ h.ru/vaca ┆ 3T12:25:4 ┆ engineer │
│           ┆ manager   ┆           ┆ оятельно  ┆   ┆           ┆ ncy/12941 ┆ 2+0300    ┆          │
│           ┆           ┆           ┆ про…      ┆   ┆           ┆ 028…      ┆           ┆          │
│ 129155851 ┆ DevOps    ┆ Сербия    ┆ Experienc ┆ … ┆ з/п не    ┆ https://h ┆ 2026-01-2 ┆ AI       │
│           ┆ Engineer  ┆           ┆ e with    ┆   ┆ указана   ┆ h.ru/vaca ┆ 3T09:18:1 ┆ engineer │
│           ┆           ┆           ┆ Docker    ┆   ┆           ┆ ncy/12915 ┆ 5+0300    ┆          │
│           ┆           ┆           ┆ (deploy…  ┆   ┆           ┆ 585…      ┆           ┆          │
│ 129386501 ┆ LLMOps/AI ┆ Санкт-Пет ┆ Понимание ┆ … ┆ 120000-15 ┆ https://h ┆ 2026-01-2 ┆ AI       │
│           ┆ инженер   ┆ ербург    ┆ работы    ┆   ┆ 0000 RUR  ┆ h.ru/vaca ┆ 3T01:58:3 ┆ engineer │
│           ┆           ┆           ┆ векторных ┆   ┆           ┆ ncy/12938 ┆ 2+0300    ┆          │
│           ┆           ┆           ┆ БД …      ┆   ┆           ┆ 650…      ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 129407622 ┆ Ведущий   ┆ Санкт-Пет ┆ Опыт      ┆ … ┆ з/п не    ┆ https://h ┆ 2026-01-2 ┆ Аналитик │
│           ┆ аналитик  ┆ ербург    ┆ работы от ┆   ┆ указана   ┆ h.ru/vaca ┆ 0T11:15:1 ┆ Данных   │
│           ┆ отдела    ┆           ┆ 3 лет в   ┆   ┆           ┆ ncy/12940 ┆ 9+0300    ┆          │
│           ┆ маркет…   ┆           ┆ качеств…  ┆   ┆           ┆ 762…      ┆           ┆          │
│ 129302941 ┆ Аналитик  ┆ Ташкент   ┆ Базовые   ┆ … ┆ 6000000-8 ┆ https://h ┆ 2026-01-1 ┆ Аналитик │
│           ┆ данных    ┆           ┆ знания в  ┆   ┆ 000000    ┆ h.ru/vaca ┆ 2T14:44:2 ┆ Данных   │
│           ┆           ┆           ┆ области   ┆   ┆ UZS       ┆ ncy/12930 ┆ 2+0300    ┆          │
│           ┆           ┆           ┆ банко…    ┆   ┆           ┆ 294…      ┆           ┆          │
│ 129305407 ┆ Аналитик  ┆ Новосибир ┆ Высшее    ┆ … ┆ 88000-    ┆ https://h ┆ 2026-01-1 ┆ Аналитик │
│           ┆ данных    ┆ ск        ┆ образован ┆   ┆ RUR       ┆ h.ru/vaca ┆ 2T15:07:4 ┆ Данных   │
│           ┆           ┆           ┆ ие. Опыт  ┆   ┆           ┆ ncy/12930 ┆ 6+0300    ┆          │
│           ┆           ┆           ┆ в сфе…    ┆   ┆           ┆ 540…      ┆           ┆          │
│ 127329895 ┆ Помощник  ┆ Рязань    ┆ Приветств ┆ … ┆ 60000-    ┆ https://h ┆ 2026-01-2 ┆ Аналитик │
│           ┆ руководит ┆           ┆ уется     ┆   ┆ RUR       ┆ h.ru/vaca ┆ 0T11:18:3 ┆ Данных   │
│           ┆ еля       ┆           ┆ высшее    ┆   ┆           ┆ ncy/12732 ┆ 8+0300    ┆          │
│           ┆ отдела а… ┆           ┆ экономич… ┆   ┆           ┆ 989…      ┆           ┆          │
│ 129411416 ┆ Руководит ┆ Минск     ┆ Понимание ┆ … ┆ з/п не    ┆ https://h ┆ 2026-01-2 ┆ Аналитик │
│           ┆ ель       ┆           ┆ логики    ┆   ┆ указана   ┆ h.ru/vaca ┆ 0T11:58:5 ┆ Данных   │
│           ┆ процесса  ┆           ┆ товародви ┆   ┆           ┆ ncy/12941 ┆ 1+0300    ┆          │
│           ┆ товародв… ┆           ┆ жени…     ┆   ┆           ┆ 141…      ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [9]:
df.columns

['vacancy_id',
 'title',
 'loc',
 'requirement',
 'responsibility',
 'work_format_ids',
 'work_format_names',
 'skills',
 'company',
 'industry',
 'experience',
 'salary_from',
 'salary_to',
 'salary_currency',
 'salary_str',
 'url',
 'published_at',
 'source_vacancy']

In [7]:
df = pl.read_parquet("/Users/yakto/projects/career_agent/parser/data/*")
df.write_parquet("/Users/yakto/projects/career_agent/data_artefacts/vacancy_final.parquet")

In [25]:
df

shape: (17_576, 15)
┌────────────┬────────────┬────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ vacancy_id ┆ title      ┆ city   ┆ keywords  ┆ … ┆ salary_st ┆ url       ┆ published ┆ source_va │
│ ---        ┆ ---        ┆ ---    ┆ ---       ┆   ┆ r         ┆ ---       ┆ _at       ┆ cancy     │
│ i64        ┆ str        ┆ str    ┆ str       ┆   ┆ ---       ┆ str       ┆ ---       ┆ ---       │
│            ┆            ┆        ┆           ┆   ┆ str       ┆           ┆ datetime[ ┆ str       │
│            ┆            ┆        ┆           ┆   ┆           ┆           ┆ μs, UTC]  ┆           │
╞════════════╪════════════╪════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 124523955  ┆ Менеджер   ┆ Москва ┆ Ты любишь ┆ … ┆ 80000-    ┆ https://h ┆ 2025-08-2 ┆ Product   │
│            ┆ продукта   ┆        ┆ общаться  ┆   ┆ RUR       ┆ h.ru/vaca ┆ 7         ┆ Manager   │
│            ┆            ┆        ┆ с людьми  ┆   ┆           ┆ ncy/12452 ┆ 05:28:36  ┆           │
│            ┆            ┆        ┆ и …       ┆   ┆           ┆ 395…      ┆ UTC       ┆           │
│ 124826328  ┆ Delivery   ┆ Москва ┆ Опыт упра ┆ … ┆ з/п не    ┆ https://h ┆ 2025-09-0 ┆ Machine   │
│            ┆ Manager /  ┆        ┆ вления    ┆   ┆ указана   ┆ h.ru/vaca ┆ 3         ┆ Learning  │
│            ┆ Деливери   ┆        ┆ ИТ-проект ┆   ┆           ┆ ncy/12482 ┆ 11:34:11  ┆           │
│            ┆ ме…        ┆        ┆ ами о…    ┆   ┆           ┆ 632…      ┆ UTC       ┆           │
│ 124964211  ┆ DevOps-инж ┆ Москва ┆ Понимание ┆ … ┆ з/п не    ┆ https://h ┆ 2025-09-0 ┆ Python    │
│            ┆ енер в     ┆        ┆ основ     ┆   ┆ указана   ┆ h.ru/vaca ┆ 5         ┆ Developer │
│            ┆ команду    ┆        ┆ сетевых   ┆   ┆           ┆ ncy/12496 ┆ 16:00:35  ┆           │
│            ┆ User …     ┆        ┆ технол…   ┆   ┆           ┆ 421…      ┆ UTC       ┆           │
│ 124374678  ┆ Системный  ┆ Москва ┆ Знание    ┆ … ┆ 170000-   ┆ https://h ┆ 2025-08-2 ┆ Web       │
│            ┆ аналитик/А ┆        ┆ основ htt ┆   ┆ RUR       ┆ h.ru/vaca ┆ 2         ┆ Analyst   │
│            ┆ налитик    ┆        ┆ p-запросо ┆   ┆           ┆ ncy/12437 ┆ 11:36:06  ┆           │
│            ┆ да…        ┆        ┆ в, оп…    ┆   ┆           ┆ 467…      ┆ UTC       ┆           │
│ 123978202  ┆ PowerPlatf ┆ Москва ┆ Strong    ┆ … ┆ з/п не    ┆ https://h ┆ 2025-08-1 ┆ Data      │
│            ┆ orm        ┆        ┆ skills in ┆   ┆ указана   ┆ h.ru/vaca ┆ 2         ┆ Engineer  │
│            ┆ Engineer   ┆        ┆ algorithm ┆   ┆           ┆ ncy/12397 ┆ 14:03:02  ┆           │
│            ┆            ┆        ┆ s, <…     ┆   ┆           ┆ 820…      ┆ UTC       ┆           │
│ …          ┆ …          ┆ …      ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 124789341  ┆ Преподават ┆ Москва ┆ Знание    ┆ … ┆ 50000-    ┆ https://h ┆ 2025-09-0 ┆ Python    │
│            ┆ ель курса  ┆        ┆ или опыт  ┆   ┆ RUR       ┆ h.ru/vaca ┆ 2         ┆ Developer │
│            ┆ Backend-ра ┆        ┆ работы    ┆   ┆           ┆ ncy/12478 ┆ 15:47:05  ┆           │
│            ┆ …          ┆        ┆ как мин…  ┆   ┆           ┆ 934…      ┆ UTC       ┆           │
│ 123899058  ┆ Оператор   ┆ Москва ┆ Имеете    ┆ … ┆ 40000-600 ┆ https://h ┆ 2025-09-0 ┆ Аналитик  │
│            ┆ по         ┆        ┆ базовые   ┆   ┆ 00 RUR    ┆ h.ru/vaca ┆ 7         ┆ данных    │
│            ┆ обработке  ┆        ┆ навыки    ┆   ┆           ┆ ncy/12389 ┆ 10:24:25  ┆           │
│            ┆ заявок     ┆        ┆ работы с… ┆   ┆           ┆ 905…      ┆ UTC       ┆           │
│ 125035681  ┆ Менеджер   ┆ Москва ┆ Опыт      ┆ … ┆ 75000-750 ┆ https://h ┆ 2025-09-0 ┆ Project   │
│            ┆ проекта    ┆        ┆ работы от ┆   ┆ 00 RUR    ┆ h.ru/vaca ┆ 8         ┆ Manager   │
│            ┆ (строитель ┆        ┆ 1 года в  ┆   ┆           ┆ ncy/12503 ┆ 11:47:24  ┆           │
│            ┆ ств…       ┆        ┆ аналог…   ┆   ┆           ┆ 568…      ┆ UTC       ┆           │
│ 124426292  ┆ DataOps/De ┆ Москва ┆ Опыта     ┆ … ┆ з/п не    ┆ https://h ┆ 2025-08-2 ┆ Data      │
│            ┆ vOps       ┆        ┆ работы по ┆   ┆ указана   ┆ h.ru/vaca ┆ 5         ┆ Engineer  │
│            ┆ инженер на ┆        ┆ направлен ┆   ┆           ┆ ncy/12442 ┆ 08:06:50  ┆           │
│            ┆ Data…      ┆        ┆ ию Da…    ┆   ┆           ┆ 629…      ┆ UTC       ┆           │
│ 123895928  ┆ Помощник   ┆ Москва ┆ Высшее    ┆ … ┆ 100000-12 ┆ https://h ┆ 2025-09-0 ┆ Project   │
│            ┆ Руководите ┆        ┆ техническ ┆   ┆ 0000 RUR  ┆ h.ru/vaca ┆ 7         ┆ Manager   │
│            ┆ ля проекта ┆        ┆ ое образо ┆   ┆           ┆ ncy/12389 ┆ 09:47:31  ┆           │
│            ┆            ┆        ┆ вание…    ┆   ┆           ┆ 592…      ┆ UTC       ┆           │
└────────────┴────────────┴────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [26]:
df1.schema

Schema([('vacancy_id', Int64),
        ('title', String),
        ('loc', String),
        ('requirement', String),
        ('responsibility', String),
        ('work_format_ids', List(String)),
        ('work_format_names', List(String)),
        ('skills', List(String)),
        ('company', String),
        ('industry', String),
        ('experience', String),
        ('salary_from', Int64),
        ('salary_to', Int64),
        ('salary_currency', String),
        ('salary_str', String),
        ('url', String),
        ('published_at', Datetime(time_unit='us', time_zone='UTC')),
        ('source_vacancy', String)])

In [27]:
df.schema

Schema([('vacancy_id', Int64),
        ('title', String),
        ('city', String),
        ('keywords', String),
        ('skills', List(String)),
        ('company', String),
        ('industry', String),
        ('experience', String),
        ('salary_from', Int64),
        ('salary_to', Int64),
        ('salary_currency', String),
        ('salary_str', String),
        ('url', String),
        ('published_at', Datetime(time_unit='us', time_zone='UTC')),
        ('source_vacancy', String)])

In [28]:
# import requests

# def get_vacancies_api():
#     url = "https://api.hh.ru/vacancies"

#     params = {
#         'text': 'IT',
#         'area': 1,
#         'per_page': 100,
#         'page': 0
#     }

#     headers = {
#         'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
#     }

#     try:
#         response = requests.get(url, params=params, headers=headers)
#         response.raise_for_status()

#         data = response.json()

#         results = []
#         for item in data['items']:
#             results.append({
#                 'id': item['id'],
#                 'title': item['name'],
#                 'company': item['employer']['name'],
#                 'salary_from': item['salary']['from'] if item['salary'] else None,
#                 'salary_to': item['salary']['to'] if item['salary'] else None,
#                 'salary_currency': item['salary']['currency'] if item['salary'] else None,
#                 'url': item['alternate_url']
#             })

#         return results

#     except requests.RequestException as e:
#         print(f"Ошибка при запросе: {e}")
#         return []

# vacancies = get_vacancies_api()
# vacancies

https://shakhbanov.org/kak-ispolzovat-api-hhru-dlya-parsinga-sbora-vakansiy-v-oblasti-data-science/?ysclid=mf5snc647t874403230

In [29]:
# Функция для получения вакансий
def get_vacancies(city, vacancy, page):
    url = 'https://api.hh.ru/vacancies'
    params = {
        'text': f"{vacancy}",
        'per_page': 100,
        'page': page
    }
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
    }

    response = requests.get(url, params=params, headers=headers)
    response.raise_for_status()
    return response.json()

In [30]:
# Функция для получения навыков вакансии
def get_vacancy_skills(vacancy_id: str) -> List[str]:
    """Получает навыки для конкретной вакансии"""
    try:
        url = f"https://api.hh.ru/vacancies/{vacancy_id}"
        response = requests.get(url)
        response.raise_for_status()
        data = response.json()

        # Извлекаем названия навыков
        skills = data.get('key_skills', [])
        if skills and isinstance(skills, list):
            # Если навыки представлены как список словарей
            if isinstance(skills[0], dict) and 'name' in skills[0]:
                return [skill['name'] for skill in skills]
            # Если навыки представлены как список строк
            elif isinstance(skills[0], str):
                return skills
        return []
    except Exception as e:
        logging.error(f"Ошибка при получении навыков для вакансии {vacancy_id}: {e}")
        return []

In [31]:
# Функция для получения отрасли компании
def get_industry(company_id):
    # Получение отрасли компании по ее идентификатору
    if company_id is None:
        return 'Unknown'

    url = f'https://api.hh.ru/employers/{company_id}'
    response = requests.get(url)
    if response.status_code == 404:
        return 'Unknown'
    response.raise_for_status()
    data = response.json()

    if 'industries' in data and len(data['industries']) > 0:
        return data['industries'][0].get('name')
    return 'Unknown'

In [32]:
# Функция для парсинга вакансий
# Функция для парсинга вакансий
def parse_vacancies_incremental(city_id: int = 1, city: str = "Москва") -> pl.DataFrame:
    """Версия с постепенным наращиванием DataFrame"""
    vacancies = [
        # 'Computer vision',
        # 'Data Analyst', 'Data Engineer', 'Data Science', 'Data Scientist', 'ML Engineer',
        # 'MLOps инженер', 'AI','AI research',
        # 'AI research',
        'AI engineer',
        'Deep Learning', 'LLM','Time series',
    ]

    df_final = None
    cities = {
        'Москва': 1,
    }
    for city, city_id in cities.items():
        for vacancy in vacancies:
            page = 0
            vacancy_data = []
            logging.info(f"Парсинг вакансии: {vacancy}")
            print(f"Парсинг вакансии: {vacancy}")

            while True:
                try:
                    data = get_vacancies(city_id, vacancy, page)
                    if page==0:
                        print(f"Число страниц по запросу {data.get('pages')}")
                    if not data.get('items'):
                        break

                    for item in data['items']:
                        salary_data = item.get('salary')
                        if salary_data is None:
                            salary_from = salary_to = salary_currency = None
                            salary_str = "з/п не указана"
                        else:
                            salary_from = salary_data.get('from')
                            salary_to = salary_data.get('to')
                            salary_currency = salary_data.get('currency')
                            salary_str = f"{salary_from or ''}-{salary_to or ''} {salary_currency or ''}"

                        skills_list = get_vacancy_skills(item['id'])
                        industry = get_industry(item['employer'].get('id'))

                        # Извлекаем данные по формату работы
                        work_format = item.get('work_format', [])
                        work_format_ids = [fmt['id'] for fmt in work_format]
                        work_format_names = [fmt['name'] for fmt in work_format]

                        record = {
                            'vacancy_id': item['id'],
                            'title': item['name'],
                            'loc': item['area']['name'],
                            'requirement': item['snippet'].get('requirement', ''),
                            'responsibility': item['snippet'].get('responsibility', ''),
                            'work_format_ids': work_format_ids,
                            'work_format_names': work_format_names,
                            'skills': skills_list,
                            'company': item['employer']['name'],
                            'industry': industry,
                            'experience': item['experience'].get('name', 'Не указан'),
                            'salary_from': salary_from,
                            'salary_to': salary_to,
                            'salary_currency': salary_currency,
                            'salary_str': salary_str,
                            'url': item['alternate_url'],
                            'published_at': item.get('published_at'),
                            'source_vacancy': vacancy
                        }

                        vacancy_data.append(record)

                    if page >= 15:
                        print(f"Страницы {page} из {data.get('pages')} закончились")
                        break

                    page += 1

                except requests.HTTPError as e:
                    logging.error(f"Ошибка при обработке вакансии {vacancy}, страница {page}: {e}")
                    print(f"Ошибка при обработке вакансии {vacancy}, страница {page}: {e}")
                    continue
            time.sleep(random.uniform(1, 2))
            # Создаем DataFrame для текущей вакансии и объединяем с основным
            if vacancy_data:
                df_current = pl.DataFrame(vacancy_data)
                
                df_current.write_parquet(f"data/{vacancy}.parquet")


    # # Обрабатываем финальный DataFrame
    # if df_final is not None:
    #     df_final = df_final.with_columns([
    #         pl.col('published_at').str.strptime(pl.Datetime, format='%Y-%m-%dT%H:%M:%S%z'),
    #         pl.col('salary_from').cast(pl.Int64),
    #         pl.col('salary_to').cast(pl.Int64),
    #     ]).unique(subset=['vacancy_id'])

    #     logging.info(f"Спаршено {len(df_final)} уникальных вакансий")
    #     print(f"Спаршено {len(df_final)} уникальных вакансий")
    #     return df_final
    # else:
    #     return pl.DataFrame()

In [33]:
df = parse_vacancies_incremental()
df = df.with_columns(pl.col('vacancy_id').cast(pl.Int64).alias('vacancy_id'))

Парсинг вакансии: AI engineer
Число страниц по запросу 11

ERROR:root:Ошибка при получении навыков для вакансии 129722692: 403 Client Error: Forbidden for url: https://api.hh.ru/vacancies/129722692
ERROR:root:Ошибка при получении навыков для вакансии 129685131: 403 Client Error: Forbidden for url: https://api.hh.ru/vacancies/129685131
ERROR:root:Ошибка при получении навыков для вакансии 126508597: 403 Client Error: Forbidden for url: https://api.hh.ru/vacancies/126508597
ERROR:root:Ошибка при получении навыков для вакансии 129725571: 403 Client Error: Forbidden for url: https://api.hh.ru/vacancies/129725571
ERROR:root:Ошибка при получении навыков для вакансии 129674959: 403 Client Error: Forbidden for url: https://api.hh.ru/vacancies/129674959
ERROR:root:Ошибка при получении навыков для вакансии 129689141: 403 Client Error: Forbidden for url: https://api.hh.ru/vacancies/129689141
ERROR:root:Ошибка при получении навыков для вакансии 129689142: 403 Client Error: Forbidden for url: https://api.hh.ru/vacancies/129689142
ERROR:root:Ошибка при получении навыков для вакансии 129689143: 403 Client Error: Forbidden for url: https://api.hh.ru/vacancies/129689143
ERROR:root:Ошибка при получении навыков для вакансии 129749985: 403 Client Error: Forbidden for url: https://api.hh.ru/vacancies/129749985
ERROR:root:Ошибка при получении навыков для вакансии 129663537: 403 Client Error: Forbidden for url: https://api.hh.ru/vacancies/129663537
ERROR:root:Ошибка при получении навыков для вакансии 129706425: 403 Client Error: Forbidden for url: https://api.hh.ru/vacancies/129706425
ERROR:root:Ошибка при получении навыков для вакансии 129419938: 403 Client Error: Forbidden for url: https://api.hh.ru/vacancies/129419938
ERROR:root:Ошибка при получении навыков для вакансии 129749059: 403 Client Error: Forbidden for url: https://api.hh.ru/vacancies/129749059
ERROR:root:Ошибка при получении навыков для вакансии 129699257: 403 Client Error: Forbidden for url: https://api.hh.ru/vacancies/129699257
ERROR:root:Ошибка при получении навыков для вакансии 129320722: 403 Client Error: Forbidden for url: https://api.hh.ru/vacancies/129320722
ERROR:root:Ошибка при получении навыков для вакансии 129017943: 403 Client Error: Forbidden for url: https://api.hh.ru/vacancies/129017943
ERROR:root:Ошибка при получении навыков для вакансии 129273670: 403 Client Error: Forbidden for url: https://api.hh.ru/vacancies/129273670
ERROR:root:Ошибка при получении навыков для вакансии 129402707: 403 Client Error: Forbidden for url: https://api.hh.ru/vacancies/129402707
ERROR:root:Ошибка при получении навыков для вакансии 129724321: 403 Client Error: Forbidden for url: https://api.hh.ru/vacancies/129724321
ERROR:root:Ошибка при получении навыков для вакансии 129730114: 403 Client Error: Forbidden for url: https://api.hh.ru/vacancies/129730114
ERROR:root:Ошибка при получении навыков для вакансии 128936571: 403 Client Error: Forbidden for url: https://api.hh.ru/vacancies/128936571

KeyboardInterrupt:

In [ ]:
df_unique = df.unique(subset=["vacancy_id"], keep="first")
df

In [ ]:
df

In [ ]:
df.write_parquet("vacancy.parquet")

In [ ]:
df = pl.read_parquet("vacancy.parquet")

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

# Сохранить на Google Drive
df.write_parquet('/content/drive/MyDrive/vacancy.parquet')

In [ ]:
# Если keywords содержит строки типа "Python, ML, SQL"
# df = df.with_columns(
#     pl.col('skills').str.split(',')  # Разделяем по запятым
# )

# Теперь можно использовать explode
keyword_counts = df.explode('skills').group_by('skills').count()

In [ ]:
df

In [ ]:
keyword_counts.sort('count',descending=True)[0:10]